version: '3.1'
services:
  stats-server:
    build:
      context: .
      dockerfile: stats-service/stats-service-server/Dockerfile
    image: stats_server_image
    container_name:
      stats_server_container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/explorewithme
      - POSTGRES_DB=explorewithme
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  stats-db:
    image: postgres:14-alpine
    volumes:
      - /var/lib/postgresql/data/
    container_name:
      db_stats_container
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=explorewithme
      - DB_NAME=explorewithme
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  ewm-service:
    build:
      context: .
      dockerfile: main-service/Dockerfile
    image: main-service_image
    container_name:
      main-service_container
    ports:
      - "8080:8080"
    depends_on:
      - stats-server

  ewm-db:
    image: postgres:14-alpine
